#!/bin/bash
#SBATCH -p normal256
#SBATCH -J __jobname__
#SBATCH --nodes=__nb_nodes__
#SBATCH --time "__job_walltime__"
#SBATCH --exclusiv
#SBATCH -o __jobname__.o%j

NNODE=__nb_nodes__
NTASK=__ntasks_by_node__
NOPMP=__nb_threads__
if [ "__ntasks_tot__" == "__ntasks__" ]
then
  let "NPROC=$NNODE*$NTASK"
else
  NPROC=__ntasks__
fi
NPROC_IO=__nb_proc_io__

